name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: your-docker-registry
  IMAGE_NAME: your-image-name
  IMAGE_TAG: ${{ github.sha }}
  KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

    - name: Push Docker image
      run: docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

    - name: Update Kubernetes Deployment
      uses: appleboy/kubectl-action@v0.2.0
      with:
        kubeconfig: ${{ env.KUBECONFIG_DATA }}
        command: set image deployment.v1.apps/app-name app-name=${{ env.DOCKER_REGISTRY }}/$IMAGE_NAME:$IMAGE_TAG
        namespace: your-namespace