name: Deploy to Production Demo

on:
  push:
    branches: [ main ]

env:
  DOCKER_REGISTRY: registry.lerndevops.click

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub 
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t monitor-app:${{ github.sha }} .

    - name: Tag Docker image with git sha
      run: docker tag monitor-app:${{ github.sha }} ${{ env.DOCKER_REGISTRY }}/monitor-app:${{ github.sha }}

    - name: Push Docker image
      run: docker push ${{ env.DOCKER_REGISTRY }}/monitor-app:${{ github.sha }}

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER_IP }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          ls